export const translations = {
  es: {
    companyName: 'China Harbour Engineering Company Limited',
    welcomeMessage: 'Bienvenido al entorno digital diseñado para el Sistema Integrado de Gestión',
    favorites: 'FAVORITOS',
    applications: 'APLICACIONES',
    navigationMap: 'MAPA DE NAVEGACIÓN',
    processMap: 'MAPA DE PROCESOS',
    admin: 'ADMINISTRACIÓN',
    noFavorites: 'No tienes módulos favoritos.',
    noModules: 'No hay módulos en esta categoría.',
    logout: 'Cerrar Sesión',
    edit: 'Editar',
    delete: 'Eliminar',
    addModule: 'Agregar Módulo',
    editModule: 'Editar Módulo',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirmDelete: '¿Estás seguro de que quieres eliminar este módulo?',
    name_es: 'Nombre (Español)',
    name_en: 'Nombre (Inglés)',
    name_zh: 'Nombre (Chino)',
    category: 'Categoría',
    url: 'URL',
    icon: 'Ícono (Nombre de Heroicon)',
    description: 'Descripción (Opcional)',
  },
  en: {
    companyName: 'China Harbour Engineering Company Limited',
    welcomeMessage: 'Welcome to the digital environment designed for the Integrated Management System',
    favorites: 'FAVORITES',
    applications: 'APPLICATIONS',
    navigationMap: 'NAVIGATION MAP',
    processMap: 'PROCESS MAP',
    admin: 'ADMIN',
    noFavorites: 'You have no favorite modules.',
    noModules: 'There are no modules in this category.',
    logout: 'Logout',
    edit: 'Edit',
    delete: 'Delete',
    addModule: 'Add Module',
    editModule: 'Edit Module',
    save: 'Save',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete this module?',
    name_es: 'Name (Spanish)',
    name_en: 'Name (English)',
    name_zh: 'Name (Chinese)',
    category: 'Category',
    url: 'URL',
    icon: 'Icon (Heroicon Name)',
    description: 'Description (Optional)',
  },
  zh: {
    companyName: '中国港湾工程有限责任公司',
    welcomeMessage: '欢迎来到为综合管理系统设计的数字环境',
    favorites: '收藏夹',
    applications: '应用',
    navigationMap: '导航图',
    processMap: '流程图',
    admin: '管理',
    noFavorites: '您没有收藏的模块。',
    noModules: '此类别中没有模块。',
    logout: '登出',
    edit: '编辑',
    delete: '删除',
    addModule: '添加模块',
    editModule: '编辑模块',
    save: '保存',
    cancel: '取消',
    confirmDelete: '您确定要删除此模块吗？',
    name_es: '名称（西班牙语）',
    name_en: '名称（英语）',
    name_zh: '名称（中文）',
    category: '类别',
    url: '链接地址',
    icon: '图标 (Heroicon 名称)',
    description: '描述（可选）',
  },
};
